---
- name: Initial task
  file:
    path: '{{home_dir}}/projects'
    state: directory
  become: no

- name: Populate etc/
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key  }}={{ item.value }}"
  with_items: "{{ environment_data }}"

- name: Load variables
  shell: 'LC_ALL=en_US.utf-8 & LANG=en_US.utf-8'
  become: no

- name: Add repo
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install python3.8
  apt:
    pkg:
    - python3.8
    - python3.8-distutils
    - python3-pip
    state: present
    update_cache: yes

- name: Copy keys
  copy:
    src: '~/.ssh/id_rsa'
    dest: '{{home_dir}}/.ssh/'
    mode: 0600
  become: no

- name: Copy .gitconfig file
  copy:
    src: '~/.gitconfig'
    dest: '{{home_dir}}/'
  become: no

- name: Git clone ck-modtools
  git:
    repo: git@github.com:kubanacx/ck-modtools.git
    dest: '{{home_dir}}/projects/ck-modtools'
    accept_hostkey: yes
  become: no

- name: Install pipenv
  pip:
    name: pipenv
    state: forcereinstall
